#include <SFML/Graphics.hpp>
#include <iostream>
#include <fstream>
#include <cerrno>
#include <cstring>
#include <algorithm>
#include <string_view>
#include <vector>
#include <cassert>
#include <string>
#include <map>
#include <stdio.h>
#include <string>
#include <sstream>
#include <functional>
#include <list>
#include <memory>
#include <optional>
#include <string>
#include <exception>
#include <iostream>
#include <string>
